const ACTION_PREFIX = 'reactjs-learning';

const CATEGORY_ACTION_PREFIX = `${ACTION_PREFIX}/Category/`;

export const REMOVE_CATEGORY = `${CATEGORY_ACTION_PREFIX}REMOVE_CATEGORY`;
export const ADD_CATEGORY = `${CATEGORY_ACTION_PREFIX}ADD_CATEGORY`;
export const UPDATE_CATEGORY = `${CATEGORY_ACTION_PREFIX}UPDATE_CATEGORY`;

const TODO_ACTION_PREFIX = `${ACTION_PREFIX}/Todo/`;

export const ADD_TODO = `${TODO_ACTION_PREFIX}ADD_TODO`;
export const REMOVE_TODO = `${TODO_ACTION_PREFIX}REMOVE_TODO`;
export const UPDATE_TODO = `${TODO_ACTION_PREFIX}UPDATE_TODO`;
