export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const UPDATE_TODO_FILTER = 'UPDATE_TODO_FILTER';
export const UPDATE_CATEGORY_LIST = 'UPDATE_CATEGORY_LIST';

