export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const UPDATE_TODO_FILTER = 'UPDATE_TODO_FILTER';

export const UPDATE_CATEGORY_LIST = 'UPDATE_CATEGORY_LIST';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const REMOVE_CATEGORY_TODOS = 'REMOVE_CATEGORY_TODOS';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY';

export const UPDATE_CURRENT_TODO = 'UPDATE_CURRENT_TODO';
